### ISSUE TITLE
Center resulting image

### ISSUE THREAD

**Issue by dippa-1** [joethei/obsidian-plantuml#18]
Hi,
I would like to center the resulting image.
Putting `<center> ... </center>` around the code doesn't work because it will view the plantuml code as plain text.

Is there a way to do that?

Thanks

**Comment by joethei** [comment]
This css snippet will the output of the png and svg renderer.
```css
div.block-language-plantuml{
	text-align: center;
}

div.block-language-plantuml-svg{
	text-align: center;
}
```

For a single diagram you can build a snippet with the [Markdown Attributes](obsidian://show-plugin?id=markdown-attributes) plugin.
